## 新手上路
--------
### 一个简单的虚构示例
```{r}
x <- rnorm(5) #赋值操作，创建一个名为x的向量对象，包含5个来自标准正态分布的随机偏差。
x #输出向量x
#婴儿年龄与体重
age <- c(1,3,5,2,11,9,3,9,12,3) #函数c()以向量形式赋值
mean(age) #mean()函数求平均年龄
weight <- c(4.4,5.3,7.2,5.2,8.5,7.3,6.0,10.4,10.2,6.1)
mean(weight) #mean()函数求平均体重
sd(weight) #sd()函数求标准差
cor(age,weight) #cor()求线性相关度
plot(age,weight) #画年龄与体重的散点图
#q() #退出程序
```
> 小提示：*要想了解R能够作出何种图形，在命令行中运行demo(graphics)即可。其他的演示还有demo(Hershey)、demo(persp)、demo(image)。要看到完整的演示列表，不加参数直接运行demo()即可。*
```{r}
#demo(graphics)
```

### 获取帮助
``` {r}
#help.start() #打开帮助文档首页
#help("mean") #查看函数mean的帮助，引号可以省略
#?mean        #同上
#help.search("mean") #以mean为关键词搜索本地帮助文档
#??mean              #同上
#example("mean") #函数mean的使用示例
#RSiteSearch("mean") #以mean为关键词搜索在线文档和邮件列表存档
apropos("mean", mode="function") #列出名称中含有mean的所有可用函数
#data() #列出当前已加载包中所含有的所有可用示例数据集
#vignette() #列出当前已安装包中所有可用的vignette文档
#vignette("mean") #为主题mean显示指定的vignette文档
```

### 工作空间
```{r}

getwd() #查看当前的工作目录
#setwd(mydirectory)#修改当前的工作目录为mydirectory,路径尽量使用正斜杠/，因为反斜杠\是转义符，且无法自动创建一个不存在的目录,可使用函数dir.creat()来创建新目录，然后再进行目录设置
ls() #列出当前工作空间中的对象
#rm(objectlist) #删除一个或多个对象
#help(options) #显示可用选项的说明
#options()# 显示或设置当前选项
#history(10) #显示最近使用过的10个命令(默认值为25)
#savehistory("myfile") #保存命令历史到文件myflie中
#loadhistory("myfile") #载入一个命令历史文件
#save.image("myfile") #保存工作空间到文件myfile中
#save(objectlist, file="myfile") #保存指定对象到一个文件中
#load("myfie") #读取一个工作空间到当前会话中
## 示例
#options()
options(digit=3) #3位小数
x <- runif(20) #包含20个均匀分布随机变量的向量
x
summary(x)#数据的摘要统计量
hist(x) #数据分布的直方图

```

### 输入与输出
> * 输入：函数source("filename")可在当前会话中执行一个脚本(可含路径，执行包含文件中的R语句集合。依照惯例，脚本文本以.R为扩展名，也可以不遵守。)
> * 文本输出：函数sink("filename")将输出重定位于文件filename中(默认情况下会覆盖已存在的同名文件)，使用参数append=TRUE可以将文件追加到已存在同名文件后，而不覆盖它。而参数split=TRUE可将输出同时发送到屏幕与文件中。不加参数调用sink()将仅向屏幕返回输出结果。
> * 图形输出：虽然sink()可以重定向文本输出，但它对图形输出并无影响。图像输出函数主要有以下一些：
     + pdf("filename.pdf")
     + win.metafile("filename.wmf")
     + png("filename.png")
     + jpeg("filename.jpg")
     + bmp("filename.bmp")
     + postscript("filename.ps")

#### 示例
```{r}
sink("myoutput", append=TRUE, split=TRUE)
pdf("mygraph.pdf")
source("1.R")

```
### 包
> * 包的安装：install.packages("packagesname")
> * 包的更新：update.packages()
> * 包的载入：library("packagesname")

>   包的使用方法:
  + help(package="package_name") #查看包的帮助文件
  + 从CRAN下载pdf帮助手册
  
#### R语言编程中常见错误
1. 使用了错误的大小写，如help()才是正确的；
2. 忘记了必要的引号，如install.packages("knitr");
3. 在函数调用时忘记使用括号，如help();
4. 在windows上路径名使用了\\；
5. 使用了一个尚未载入的包。

### 批处理
> 如何以批处理模式运行R与使用的操作系统有关。在Linux或Mac OS X系统下，可以在终端窗口中使用如下命令：R CMD BATCH options infile outfile;windows则需使用："R.exe" CMD BATCH options infile outfile

### 将输出作为输入――结果的重用
#### 示例――汽车重量与行驶里程
``` {r}
wt <- c(1,2,3,4,6,8,12) #汽车重量
mpg <- c(12,11,10,9,7,5,1) #每加仑行驶英里数
lmfit <- lm(mpg~wt)  #线性回归并保存在一个对象中
summary(lmfit) #显示分析结果的统计概要
#plot(lmfit) #生成回归诊断图形
cook <- cooks.distance(lmfit) #计算影响度量统计量并保存在一个对象中
plot(cook) #进行绘图
predict(lmfit,5) #在新的车身重量数据上对每加仑行驶的英里数进行预测

```

### 示例实践
1. 打开帮助文档首页: help.start()
2. 安装vcd包: install.packages("vcd")
3. 列出此包中可用的函数和数据集: help(package="vcd")
4. 载入这个包并阅读数据集Arthritis的描述: library(vcd)
5. 示数据集Arthritis的内容: help(Arthritis)
6. 运行数据集Arthritis自带的示例: example(Arthritis)
7. 显示数据集Arthritis的内容: Arthritis

```{r}
#help(package = "vcd")
library(vcd)
#help(Arthritis)
Arthritis
example(Arthritis)
```

## 创建数据集
> 数据集通常是由数据构成的一个矩形数组，行表示观测，列表示变量。R中有许多用于存储数据的结构，包括标量、向量、数组、数据框和列表。R可以处理的数据类型（模式）包括数值型、字符型、逻辑型（TRUE/FALSE）、复数型（虚数）和原生型（字节）。
----

### 数据结构
> 在R中，对象（object）是指可以赋值给变量的任何事物，包括常量、数据结构、函数，甚至图形。数据框（data frame）是R中用于存储数据的一种结构：列表示变量，行表示观测。在同一个数据框中可以存储不同类型（如数值型、字符型）的变量。数据框将是你用来存储数据集的主要数据结构。

#### 向量
> 向量是用于存储数值型、字符型或逻辑型数据的一维数组。执行组合功能的函数c()可用来创建向量。各类向量如下例所示：
* a <- c(1, 2, 5, 3, 6, -2, 4)
* b <- c("one", "two", "three")
* c <- c(TRUE, TRUE, TRUE, FALSE, TRUE, FALSE)
  > 注意：注意，单个向量中的数据必须拥有相同的类型或模式（数值型、字符型或逻辑型）。标量其实可以看作只有一个元素的向量。

> 向量元素的访问
* a[c(2,4)] #向量a的第2个与第4个元素
* a[3] #向量a的第3个元素
* a[2:6] #向量a的第2到6个元素
R示例

```{r}
a <- c(1,2, 5, 3, 6, -2, 4)
b <- c("one", "two", "three")
c <- c(TRUE, TRUE, TRUE, FALSE, TRUE, FALSE)
a[c(2,4)]
b[3]
c[3:5]
```










