## 第一章 引言

### 1.1 ggplot2简介
`ggplot2`是一个用于绘制统计图形（**数据图形**）的R软件包。与其他大多图形软件包不同，`ggplot2`有一套**图形语法**(Grammar of Graphics)支持。
`ggplot2`由一系列独立的图形部件组成，并能以许多不同的方式组合起来。这似乎有些困难，其实只需掌握一些核心准则和少许特例即可很容易的学习`ggplot2`。

`ggplot2`可绘制美观图形，且避免许多繁琐细节，如添加图例。绘图时，图形的每个部分可**依次构建**，而后还可进行编辑。
`ggplot2`精心挑选了一系列**预设图形**以快速绘制高质量图形。格式上的额外需求可通过**主题系统**进行定制。如此便不需太长的时间来调整图形而便于更加专注于数据的图形展示。

`ggplot2`采用了**图层的设计方式**，可从原始图层开始，先绘制原始数据，然后不断添加图形注释和统计汇总。这种绘图方式与分析中的**结构化思维**是一致的。

学习图形语法既可助你绘制出已知的图形，还可启发你创作出更佳的方案。语法体系使得`ggplot2`图形软件包不再沦为一系列特例的堆积。在**R**的基础包中，一个新图形一定是由原始的图形元素（如点和线）构成的，而很难利用现有的图形样例进行组合。而在`ggplot2`中，用于创建新图形的表达式是由高级的图形元素组成的。这些图形元素可方便地与新的数据集以及其他图形进行结合。

### 1.2 其他资源
`ggplot2`在线帮助文档：

1. [http://docs.ggplot2.org](http://docs.ggplot2.org)
2. [http://had.co.nz/gglot2](http://had.co.nz/ggplot2)

### 1.3 图形语法
**Willinson**(2005)创建了一套用于描述所有统计图形深层特性的语法规则，而**Wickham**(2010)提出了基于**Wilkinson**语法的图层图形语法，将图层作为主要考察对象嵌入**R**中。

简而言之，该套语法认为：一个统计图形就是从**数据**到**`几何对象`**(geometric object,缩写为`geom`，包括点、线、条形等)的**`图形属性`**(aesthetic attributes,缩写为`aes`，包括颜色、形状、大小等)的一个映射。此外，图形还可包含数据的**`统计变换`**(statistical transformation，缩写为`stats`)，最后绘制在一个特定的**`坐标系`**(coordinate system，缩写为`coord`)中。而**`分面`**(`facet`，指将绘图窗口划分为若干子窗口)则用于生成数据不同子集的图形。

#### 图形部件术语解释

+ 最基础部分是待可视化的**数据**(data)以及一系列将数据中变量对应到图形属性的**映射**(mapping);
+ **几何对象**(geom)代表图中可见的图形元素，如点、线、多边形等；
+ **统计变换**(stats)是对数据进行的某种汇总。如将数据分组计数以创建直方图，或将一个二维的关系用线性模型进行解释。统计变换是可选的，但通常十分有用；
+ **标度**(scale)的作用是将数据的取值映射到图形空间，例如用颜色、大小或形状来表示不同的取值。展现**标度**的常见做法是绘制图例和坐标轴；
+ **坐标系**(coord)描述数据是土河映射到图形所在平面的，同时提供看图所需轴与线。通常使用笛卡尔坐标系，亦可变换为其他类型，如极坐标和地图投影；
+ **分面**(facet)描述如何将数据分解为各个子集，以及如何对子集作图并联合进行展示。分面也叫作条件作图或网格作图。

#### 图形语法的一些局限

+ 对问题未指出应采用何种图形进行展示；
+ 为规定图形外观应该如何；
+ 仅描述静态图形，如制作交互式或动态图像需借助`rggobi`软件包。

### 1.4 ggplot2与其他图形软件包

**R**中其他的图形系统有基础图形系统、网格图形系统和trellis/lattice图形系统等。`ggplot2`与它们的区别在于：

+ **基础图形系统**是由Ross Ihaka编写的，基于**S**语言图形驱动，采用“纸-笔”绘制模型：只能在图形的顶端进行绘画，不能修改或删除已有的内容，且缺乏用户可控的表达形式。其中大多函数运行很快，但使用范围有限；
+ **网格图形系统**是一个更加丰富的图形绘制系统，由Paul Murrell开发。网格系统中的图形对象可与屏幕上的图形独立存在，且可反复修改，其中一系列的视图区可方便地对图形进行复杂布局。但只能绘制基本图形元素，而没有提供创建统计图形的工具；
+ **lattice**软件包由Deepayan Sarkar开发，利用网格图形系统实现了lattice图形系统，这是对基础绘图系统的巨大改进，方便进行条件作图，且一些作图细节可自动完成。lattice缺少一个完整的模型而难以扩展；
+ **ggplot2**初现于2005年，吸取了基础绘图系统和lattice绘图系统的有点，并具有一个强大的模型。`ggplot2`使用紧凑的语法轻松制图，且利用网格图形系统作图，可在底层对图形外观进行控制。

其他的R程序包，如`vcd`,`plotrix`,`gplots`等是针对特殊需要的图形。但目前尚未有其他的软件包能够提供绘制统计图形的统一框架。**R**中完整的图形软件包列表：[http://cran.r-project.org/web/views/Graphics.html](http://cran.r-project.org/web/views/Graphics.html)

### 1.5 关于本书

+ 第二章介绍利用`qplot`函数快速入门，好像用`plot`函数来绘制图形一样

+ 第三章介绍`ggplot2`背后得到图层图形语法；

+ 第四章阐释其中的理论，并演示如何添加图层，以及控制其中的几何对象和统计变换；

+ 第五章表述将几何对象和统计变换进行组合；

+ 第六章介绍一些常用的标度。**标度**对优化图形的感官属性十分重要，通过自定义标度可精确控制图形外观；

+ 第七章讲解坐标系和分面以控制图形元素的位置；

+ 第八章介绍主题系统，改变几何对象、统计变换和标度的默认取值，保存图形，多图放置等；

+ 第九章讨论将数据转换为ggplot2所需格式的技巧并介绍比作图命令更高级的数据汇总和处理的工具；

+ 第十章涵盖三个减少代码冗余的有用技巧：逐步修改、绘图模板和绘图函数。

+ 附录A展示如何将基础绘图系统、lattice绘图系统和GPL的语法转变为`ggplot2`的语法；

+ 附录B介绍如何手动指定颜色、形状、线条类型和大小；

+ 附录C描述`ggplot2`中网格图形对象的高级组织方式以及视图区的布局。

### 1.6 安装ggplot2

+ 命令：
```
install.packages("ggplot2")
```

### 1.7 致谢